### PR TITLE
cleanup before addentry

### LINKED ISSUE #29: Parser for category
- [ ] docs for category format
- [ ] save category into entry on add command
- [ ] add category to "Entry"

### PR DESCRIPTION
**Pull request by ongspxm**
fixes #29, #55, #77

### CODE REVIEW

**Comment by ongspxm** [comment]
@jhengy the cleanup is done, let me know if this needs to be continued

**Comment by ongspxm** [comment]
apparently, it failed on `AddressBookSystemTest:180`... this is weird... let me try fix it

**Comment by ongspxm** [comment]
the problem seems to be that when you try to do the undo command, the ui clears the command box when the undo command is completed, not sure if it is a bug

**Comment by ongspxm** [comment]
new findings: `deleteAllPersons` on line 92 doesnt seem to work, figuring out why

**Comment by ongspxm** [comment]
ha le lu ya, found it
`java.lang.Exception: add n/Alice Pauline p/94351253 e/alice@example.com a/123, Jurong West Ave 6, #08-111 #friends`

**Comment by ongspxm** [comment]
@anubh-v @jhengy @marvintxd @scalarmotion how do you guys wanna proceed

**Comment by scalarmotion** [comment]
Yeah that sounds fine.

**Comment by ongspxm** [comment]
oh noes... now i need to clean up the data write up

**Pull request merged**
